---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: aur-pipelines

release:
  github:
    owner: n3tuk
    name: aur-pipelines
  name_template: |-
    {{ .Version }}
  draft: true
changelog:
  disable: true
snapshot:
  version_template: >-
    {{ incpatch .Version }}~d{{ .Now.Format "0601021504" }}
checksum:
  name_template: |-
    aur-pipelines-sha512
  algorithm: sha3-512

builds:
  - id: aur-pipelines
    main: ./cmd/aur-pipelines
    binary: aur-pipelines
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    ldflags: >-
      -s -w -X 'main.Branch={{ .Branch }}' -X 'main.Commit={{ .ShortCommit }}' -X 'main.Version={{ .Version }}' -X
      'main.BuildDate={{ .Date }}' -X 'main.Architecture={{ .Runtime.Goarch }}'
    asmflags: >-
      all=-trimpath=.
    gcflags: >-
      all=-trimpath=.
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
      - arm
    goarm:
      - "7"
    goamd64:
      - v3
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - id: archive
    ids:
      - aur-pipelines
    name_template: |-
      {{ .ProjectName }}-v{{ .Version }}-{{ tolower .Os }}-{{ tolower .Arch }}
    builds_info:
      group: root
      owner: root
      mode: 0755
      mtime: 2006-01-02T15:04:05Z
    files:
      - LICENSE
